# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Simon/Desktop/lab1_2/fourBitCounter/fourBitCounter.cache/wt [current_project]
set_property parent.project_path C:/Users/Simon/Desktop/lab1_2/fourBitCounter/fourBitCounter.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  C:/Users/Simon/Desktop/lab1_2/fourBitCounter/fourBitCounter.srcs/sources_1/new/half_adder.v
  C:/Users/Simon/Desktop/lab1_2/fourBitCounter/fourBitCounter.srcs/sources_1/new/d_flipflop.v
  C:/Users/Simon/Desktop/lab1_2/fourBitCounter/fourBitCounter.srcs/sources_1/new/counter.v
  C:/Users/Simon/Desktop/lab1_2/fourBitCounter/fourBitCounter.srcs/sources_1/new/adder.v
  C:/Users/Simon/Desktop/lab1_2/fourBitCounter/fourBitCounter.srcs/sources_1/new/full_adder.v
  C:/Users/Simon/Desktop/lab1_2/fourBitCounter/fourBitCounter.srcs/sources_1/new/four_bit_counter.v
}
synth_design -top four_bit_counter -part xc7k70tfbv676-1
write_checkpoint -noxdef four_bit_counter.dcp
catch { report_utilization -file four_bit_counter_utilization_synth.rpt -pb four_bit_counter_utilization_synth.pb }
